apiVersion: benchflow.io/v1alpha1
kind: DeploymentProfile
metadata:
  name: rhaiis-raw-vllm
spec:
  platform: rhaiis
  mode: raw-vllm
  endpoint_path: /v1/models
  model_storage:
    pvc_name: models-storage
    cache_dir: /models
    mount_path: /mnt
  runtime:
    image: registry.stage.redhat.io/rhaii/vllm-cuda-rhel9:3.4.0-1776326705
    replicas: 4
    tensor_parallelism: 2
    vllm_args:
      - --max-model-len=8192
      - --enable-prefix-caching
      - --trust-remote-code
      - --gpu-memory-utilization=0.92
      - --no-enable-log-requests
