apiVersion: v1
kind: Service
metadata:
  name: gpt-oss-120b-direct
  namespace: benchflow
  labels:
    app: gpt-oss-120b-direct
    benchflow.io/benchmark-target: "true"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    llm-d.ai/inference-serving: "true"
    llm-d.ai/inferenceServing: "true"
    llm-d.ai/model: gpt-oss-120b-llm-d-release-direct
    llm-d.ai/role: decode
