apiVersion: benchflow.io/v1alpha1
kind: Experiment
metadata:
  name: gpt-oss-120b-llm-d-release-direct
spec:
  model:
    name:
      - openai/gpt-oss-120b
  deployment_profile:
    - llm-d-inference-scheduling
    #- llm-d-precise-prefix-cache
  benchmark_profile:
    # - guidellm-concurrent-1k-1k
    # - guidellm-concurrent-heavy-heterogeneous
    # - guidellm-multi-turn
    - aiperf-mooncake-trace
  metrics_profile: detailed
  mlflow:
    tags:
      accelerator: H200
      routing_mode: direct-service
      note: "Bypasses gateway - direct service to model pods"
    experiment: michey-gpt-oss-120b-mooncake
  namespace: benchflow
  execution:
    timeout: 8h
  overrides:
    benchmark:
      request_type: text_completions
    runtime:
      #node_selector:
        #kubernetes.io/hostname: psap-de-h200-cluster-6mgmp-gpu-h200-22mkm
      resources:
        requests:
          cpu: "12"
        limits:
          cpu: "12"
  target:
    base_url: http://gpt-oss-120b-direct:8000
    metrics_release_name: gpt-oss-120b-llm-d-release
